#!/usr/bin/env php
<?php

use App\Commands\ClearCache;
use App\Commands\Database\Migrate;
use App\Commands\PruneCache;
use App\Commands\StartServer;
use Symfony\Component\Console\Application;

// Include the composer autoloader
require __DIR__ . '/vendor/autoload.php';

$app = require __DIR__.'/bootstrap/app.php';
$app->boot();

$console = new Application();

try {
	$console->addCommands([
		new Migrate(),
		new StartServer(),
		new ClearCache(),
		new PruneCache()
	]);

    $console->run();

} catch (Exception $e) {
    print($e->getMessage());
}